### ISSUE TITLE
Part 1

### ISSUE THREAD

**Issue by matheussampaio** [matheussampaio/IT356#3]
## Part 1

Write a C++ program that reads in this maze file, store it suitably, and then draw it as shown above (without the circles for start and end). 
- [x] Read maze files.
- [x] Create/Show maze.
- [x] The drawing should take up the entire window.
- [x] The maze should retain its shape (aspect ratio) if the window is resized, and should be the biggest so that it tightly fits in the window.

**Comment by matheussampaio** [comment]
Closed with commit bde85d5b8f8017399524120780f4429164dfb61e.
